# Generated by Django 4.2.15 on 2024-08-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Matching_Offer_CV_App", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="name",
            field=models.CharField(default="Unknown", max_length=255),
        ),
    ]
