# Generated by Django 4.2.15 on 2024-08-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Matching_Offer_CV_App", "0002_cv_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="offer",
            name="category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
